import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

// GitHub Pages allows no HTTP headers, so the CSP ships as a meta tag injected
// at build time only (the Vite dev server relies on inline scripts). blob: is
// required for export and media preview, data: for the favicon and thumbnails,
// 'unsafe-inline' in style for framer-motion.
// 'wasm-unsafe-eval' is what lets ffmpeg.wasm compile its module: it is the
// narrow WebAssembly-only permission, and does NOT re-enable eval() for scripts.
// The core is served from our own origin (copied out of node_modules at build
// time by copyFFmpegCore), so no CDN needs allowing.
const CSP = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval' blob:",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' blob: data:",
  "media-src 'self' blob:",
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
].join('; ');

function injectCsp(): Plugin {
  return {
    name: 'inject-csp',
    apply: 'build',
    transformIndexHtml(html) {
      return {
        html,
        tags: [
          {
            tag: 'meta',
            attrs: { 'http-equiv': 'Content-Security-Policy', content: CSP },
            injectTo: 'head-prepend',
          },
        ],
      };
    },
  };
}

/**
 * Serve ffmpeg.wasm's core from our own origin at /ffmpeg/.
 *
 * The core is 32 MB, so it is copied straight out of node_modules rather than
 * committed to the repo or pushed through rollup's asset pipeline. Nothing
 * requests it until the user asks to transcode an undecodable audio track, so
 * it never weighs on a normal page load.
 */
function copyFFmpegCore(): Plugin {
  // The package exports no './package.json', so locate it through its UMD entry
  // (what ffmpeg.wasm's classic worker importScripts) and take the sibling wasm.
  const umdDir = path.dirname(require.resolve('@ffmpeg/core'));
  const files = ['ffmpeg-core.js', 'ffmpeg-core.wasm'];
  const sourceOf = (name: string) => path.join(umdDir, name);
  return {
    name: 'copy-ffmpeg-core',
    // Dev has no dist to copy into: hand the files straight off disk instead.
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const name = files.find((f) => req.url?.startsWith(`/ffmpeg/${f}`));
        if (!name) return next();
        res.setHeader(
          'Content-Type',
          name.endsWith('.wasm') ? 'application/wasm' : 'text/javascript',
        );
        fs.createReadStream(sourceOf(name)).pipe(res);
      });
    },
    async writeBundle(options) {
      const outDir = options.dir ?? 'dist';
      await fs.promises.mkdir(path.join(outDir, 'ffmpeg'), { recursive: true });
      for (const name of files) {
        await fs.promises.copyFile(sourceOf(name), path.join(outDir, 'ffmpeg', name));
      }
    },
  };
}

// The site is served from the root of the custom domain
// (https://selfcut.alegzandr.com). Set VITE_BASE to override.
const BASE_PATH = process.env.VITE_BASE ?? '/';

export default defineConfig({
  base: BASE_PATH,
  // Static landing pages (one per language, generated by
  // scripts/build-landing.mjs) and the editor SPA at /app/.
  appType: 'mpa',
  plugins: [react(), tailwindcss(), injectCsp(), copyFFmpegCore()],
  worker: {
    format: 'es',
  },
  build: {
    target: 'es2022',
    rollupOptions: {
      input: {
        landing: 'index.html',
        'landing-en': 'en/index.html',
        'landing-es': 'es/index.html',
        'landing-de': 'de/index.html',
        'landing-pt-br': 'pt-BR/index.html',
        app: 'app/index.html',
      },
    },
  },
});
