import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

// GitHub Pages allows no HTTP headers, so the CSP ships as a meta tag injected
// at build time only (the Vite dev server relies on inline scripts). blob: is
// required for export and media preview, data: for the favicon and thumbnails,
// 'unsafe-inline' in style for framer-motion.
const CSP = [
  "default-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' blob: data:",
  "media-src 'self' blob:",
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
].join('; ');

function injectCsp(): Plugin {
  return {
    name: 'inject-csp',
    apply: 'build',
    transformIndexHtml(html) {
      return {
        html,
        tags: [
          {
            tag: 'meta',
            attrs: { 'http-equiv': 'Content-Security-Policy', content: CSP },
            injectTo: 'head-prepend',
          },
        ],
      };
    },
  };
}

// The site is served from the root of the custom domain
// (https://selfcut.alegzandr.com). Set VITE_BASE to override.
const BASE_PATH = process.env.VITE_BASE ?? '/';

export default defineConfig({
  base: BASE_PATH,
  // Static landing pages (one per language, generated by
  // scripts/build-landing.mjs) and the editor SPA at /app/.
  appType: 'mpa',
  plugins: [react(), tailwindcss(), injectCsp()],
  worker: {
    format: 'es',
  },
  build: {
    target: 'es2022',
    rollupOptions: {
      input: {
        landing: 'index.html',
        'landing-en': 'en/index.html',
        'landing-es': 'es/index.html',
        'landing-de': 'de/index.html',
        'landing-pt-br': 'pt-BR/index.html',
        app: 'app/index.html',
      },
    },
  },
});
